'use client'

import { useOnlineStatus } from '@/hooks/useOnlineStatus'

/**
 * Persistent "you are offline" bar.
 *
 * Per-request errors already explain a single failed call (request() throws a
 * typed OfflineError whose message renders through handleApiError), but a
 * one-off toast does not tell you the whole app is currently useless — the user
 * is left guessing whether to keep clicking. This is the ambient signal.
 *
 * Nothing was covering this: `navigator.onLine` appeared in zero of the 263 tsx
 * files before this component.
 *
 * Uses a token-driven dot rather than an icon import — lib/icons.tsx is
 * generated by scripts/gen-icons.mjs, so adding a glyph means regenerating it,
 * and this banner does not need one.
 *
 * role="status" + aria-live so it is announced without stealing focus.
 */
export function OfflineBanner() {
  const { isOffline } = useOnlineStatus()

  if (!isOffline) return null

  return (
    <div
      role="status"
      aria-live="polite"
      data-testid="offline-banner"
      className="fixed inset-x-0 top-0 z-[60] flex items-center justify-center gap-2 border-b border-line bg-wrap px-4 py-2 text-[12.5px] text-d-text-primary shadow-sm"
    >
      <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-down" aria-hidden />
      <span>
        You&apos;re offline — showing the last loaded data. We&apos;ll reconnect automatically.
      </span>
    </div>
  )
}
